# Generated by Django 6.0.5 on 2026-07-02 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('unidades_apro', models.IntegerField()),
                ('unidaes_defect', models.IntegerField()),
                ('comentarios', models.TextField(default='Sin comentarios')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reporte', to='api_produccion.orden')),
            ],
            options={
                'db_table': 'reporte',
            },
        ),
    ]
