# Generated by Django 6.0.5 on 2026-08-01 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_produccion', '0016_estado_orden_enhol'),
        ('api_reportes', '0001_initial'),
        ('api_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='generado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to='api_usuarios.empleado'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='oblea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reporte', to='api_produccion.oblea'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='tipo_generacion',
            field=models.CharField(choices=[('auto', 'Automático'), ('manual', 'Manual')], default='auto', max_length=6),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ReporteInventario',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_generado', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo_generacion', models.CharField(choices=[('auto', 'Automático'), ('manual', 'Manual')], default='manual', max_length=6)),
                ('snapshot', models.JSONField()),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_inventario', to='api_usuarios.empleado')),
            ],
            options={
                'db_table': 'reporte_inventario',
            },
        ),
        migrations.CreateModel(
            name='ReporteKpi',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_generado', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo_generacion', models.CharField(choices=[('auto', 'Automático'), ('manual', 'Manual')], default='manual', max_length=6)),
                ('snapshot', models.JSONField()),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_kpi', to='api_usuarios.empleado')),
            ],
            options={
                'db_table': 'reporte_kpi',
            },
        ),
        migrations.CreateModel(
            name='ReporteMensual',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('fecha_generado', models.DateTimeField(auto_now_add=True)),
                ('tipo_generacion', models.CharField(choices=[('auto', 'Automático'), ('manual', 'Manual')], default='auto', max_length=6)),
                ('snapshot_produccion', models.JSONField()),
                ('snapshot_inventario', models.JSONField()),
                ('snapshot_kpi', models.JSONField()),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_mensuales', to='api_usuarios.empleado')),
            ],
            options={
                'db_table': 'reporte_mensual',
                'constraints': [models.UniqueConstraint(fields=('anio', 'mes'), name='uk_reporte_mensual_periodo')],
            },
        ),
    ]
