# Generated by Django 6.0.5 on 2026-08-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_reportes', '0002_reporte_generado_por_reporte_oblea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportekpi',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
