# Generated by Django 6.0.5 on 2026-07-23 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAlerta',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'estado_alerta',
            },
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('clave', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('unidad', models.CharField(default='Porcentaje', max_length=20)),
                ('umbralVerde', models.IntegerField(default=1, unique=True)),
                ('umbralAmarillo', models.IntegerField(default=2, unique=True)),
                ('umbralRojo', models.IntegerField(default=3, unique=True)),
            ],
            options={
                'db_table': 'kpi',
            },
        ),
        migrations.CreateModel(
            name='Semaforo',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'semaforo',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('estadoAlerta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='alerta', to='api_kpi.estadoalerta')),
            ],
            options={
                'db_table': 'alerta',
            },
        ),
        migrations.CreateModel(
            name='Historial_Alertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='historial_alertas', to='api_kpi.alerta')),
            ],
            options={
                'db_table': 'historial_alertas',
            },
        ),
        migrations.CreateModel(
            name='Registro_Kpi',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('valor', models.IntegerField()),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='registro_kpi', to='api_kpi.kpi')),
            ],
            options={
                'db_table': 'registro_kpi',
            },
        ),
    ]
