# Generated by Django 5.2.15 on 2026-07-09 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_kpi', '0001_initial'),
        ('api_produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_kpi',
            name='oblea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='registro_kpi', to='api_produccion.oblea'),
        ),
        migrations.AddField(
            model_name='historial_alertas',
            name='registroKPI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='historial_alertas', to='api_kpi.registro_kpi'),
        ),
        migrations.AddField(
            model_name='registro_kpi',
            name='semaforo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='registro_kpi', to='api_kpi.semaforo'),
        ),
        migrations.AddConstraint(
            model_name='historial_alertas',
            constraint=models.UniqueConstraint(fields=('registroKPI', 'alerta'), name='uk_historial_alertas'),
        ),
    ]
