# Generated by Django 6.0.5 on 2026-06-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_kpi', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='unidad',
            field=models.CharField(default='Porcentaje', max_length=20),
        ),
    ]
