# Generated by Django 6.0.5 on 2026-07-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_kpi', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
    ]
