# Generated by Django 5.2.15 on 2026-07-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_kpi', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_alertas',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
