# Generated by Django 6.0.5 on 2026-07-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_kpi', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_alertas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
