# Generated by Django 6.0.5 on 2026-08-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_kpi', '0008_alter_historial_alertas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_kpi',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registro_kpi',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
