# Generated by Django 6.0.5 on 2026-08-04 21:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_kpi', '0009_alter_registro_kpi_fecha_alter_registro_kpi_hora'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='historial_alertas',
            name='uk_historial_alertas',
        ),
        migrations.AddField(
            model_name='alerta',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alerta',
            name='hora',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro_kpi',
            name='alerta',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='registro_kpi', to='api_kpi.alerta'),
        ),
        migrations.DeleteModel(
            name='Historial_Alertas',
        ),
    ]
