# Generated by Django 5.2.15 on 2026-08-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_kpi', '0009_alter_historial_alertas_id'),
        ('api_kpi', '0009_alter_registro_kpi_fecha_alter_registro_kpi_hora'),
    ]

    operations = [
    ]
