# Generated by Django 6.0.5 on 2026-08-05 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_kpi', '0011_alerta_fecha_hora_db_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registro_kpi',
            name='alerta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='registro_kpi', to='api_kpi.alerta'),
        ),
    ]
