# Generated by Django 6.0.5 on 2026-08-05 14:31

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_kpi', '0012_alter_alerta_fecha_alter_alerta_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='fecha',
            field=models.DateField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='hora',
            field=models.TimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
