# Generated by Django 6.0.5 on 2026-06-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Oblea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=5)),
                ('descripcion', models.CharField(default='', max_length=25)),
                ('cantidadDies', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=5)),
                ('descripcion', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=5)),
                ('nombre', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LineaProceso',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('linea', models.CharField(default='', max_length=5)),
                ('proceso', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MaquinaPaso',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('maquina', models.CharField(default='', max_length=5)),
                ('paso', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Oblea',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('diesGenerados', models.IntegerField(default=0)),
                ('orden', models.IntegerField(default=0)),
                ('estado', models.CharField(default='', max_length=5)),
                ('tipo', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('horaIni', models.DateTimeField()),
                ('horaFin', models.DateTimeField()),
                ('fechaReg', models.DateTimeField(auto_now_add=True)),
                ('proceso', models.CharField(default='', max_length=5)),
                ('estado', models.CharField(default='', max_length=5)),
                ('empleado', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=5)),
                ('nombre', models.CharField(default='', max_length=20)),
                ('descripcion', models.CharField(default='', max_length=80)),
                ('tiempoEstimado', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Paso_Realizado',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('paso', models.CharField(default='', max_length=5)),
                ('estado', models.CharField(default='', max_length=5)),
                ('oblea', models.IntegerField(default=0)),
                ('alerta', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PasoProceso',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('paso', models.CharField(default='', max_length=5)),
                ('proceso', models.CharField(default='', max_length=5)),
                ('orden', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=5)),
                ('nombre', models.CharField(default='', max_length=20)),
                ('descripcion', models.CharField(default='', max_length=80)),
                ('imagen', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoPieza',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('proceso', models.CharField(default='', max_length=5)),
                ('pieza', models.CharField(default='', max_length=5)),
                ('cantPiezas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Semaforo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=5)),
                ('descripcion', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
