# Generated by Django 5.2.15 on 2026-07-09 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_inventario', '0001_initial'),
        ('api_kpi', '0001_initial'),
        ('api_maquinaria', '0001_initial'),
        ('api_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defecto',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'defecto',
            },
        ),
        migrations.CreateModel(
            name='Estado_Oblea',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'estado_oblea',
            },
        ),
        migrations.CreateModel(
            name='Estado_Orden',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'estado_orden',
            },
        ),
        migrations.CreateModel(
            name='Estado_Paso',
            fields=[
                ('codigo', models.CharField(default='', max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(default='Estado generico de paso', max_length=15)),
            ],
            options={
                'db_table': 'estado_paso',
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'linea',
            },
        ),
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=80)),
                ('tiempoEstimado', models.DurationField()),
            ],
            options={
                'db_table': 'paso',
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'proceso',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Oblea',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=25)),
                ('cantidadDies', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('horaIni', models.DateTimeField()),
                ('horaFin', models.DateTimeField()),
                ('fecha', models.DateTimeField(default='2026-07-05 00:00:00+0000')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orden', to='api_usuarios.empleado')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orden', to='api_produccion.estado_orden')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orden', to='api_produccion.proceso')),
                ('tipoOblea', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orden', to='api_produccion.tipo_oblea')),
            ],
            options={
                'db_table': 'orden',
            },
        ),
        migrations.CreateModel(
            name='Oblea',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('diesGenerados', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='oblea', to='api_produccion.estado_oblea')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='oblea', to='api_produccion.orden')),
            ],
            options={
                'db_table': 'oblea',
            },
        ),
        migrations.CreateModel(
            name='Paso_Realizado',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(max_length=200)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paso_realizado', to='api_kpi.alerta')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paso_realizado', to='api_produccion.estado_paso')),
                ('oblea', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paso_realizado', to='api_produccion.oblea')),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paso_realizado', to='api_produccion.paso')),
            ],
            options={
                'db_table': 'paso_realizado',
            },
        ),
        migrations.CreateModel(
            name='MaquinaPaso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='maquina_paso', to='api_maquinaria.maquina')),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='maquina_paso', to='api_produccion.paso')),
            ],
            options={
                'db_table': 'maquina-paso',
                'constraints': [models.UniqueConstraint(fields=('maquina', 'paso'), name='uk_maquina_paso')],
            },
        ),
        migrations.CreateModel(
            name='Historial_Defectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defecto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='historial_defectos', to='api_produccion.defecto')),
                ('pasoRealizado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='historial_defectos', to='api_produccion.paso_realizado')),
            ],
            options={
                'db_table': 'historial_defectos',
                'constraints': [models.UniqueConstraint(fields=('defecto', 'pasoRealizado'), name='uk_defecto_pasoRealizado')],
            },
        ),
        migrations.CreateModel(
            name='PasoProceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paso', to='api_produccion.paso')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paso', to='api_produccion.proceso')),
            ],
            options={
                'db_table': 'paso-proceso',
                'constraints': [models.UniqueConstraint(fields=('paso', 'proceso'), name='uk_paso_proceso')],
            },
        ),
        migrations.CreateModel(
            name='LineaProceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='linea_proceso', to='api_produccion.linea')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='linea_proceso', to='api_produccion.proceso')),
            ],
            options={
                'db_table': 'linea-proceso',
                'constraints': [models.UniqueConstraint(fields=('linea', 'proceso'), name='uk_linea_proceso')],
            },
        ),
        migrations.CreateModel(
            name='ProcesoPieza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantPiezas', models.IntegerField(default=0)),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='proceso_pieza', to='api_inventario.pieza')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='proceso_pieza', to='api_produccion.proceso')),
            ],
            options={
                'db_table': 'proceso-pieza',
                'constraints': [models.UniqueConstraint(fields=('proceso', 'pieza'), name='uk_proceso_pieza')],
            },
        ),
    ]
