# Generated by Django 6.0.5 on 2026-07-01 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_produccion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oblea',
            name='tipo',
        ),
        migrations.AddField(
            model_name='orden',
            name='tipoOblea',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='orden', to='api_produccion.tipo_oblea'),
        ),
    ]
