# Generated by Django 5.2.15 on 2026-07-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oblea',
            name='codigoQR',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
