# Generated by Django 6.0.5 on 2026-06-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Paso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=5)),
                ('descripcion', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
