# Generated by Django 6.0.5 on 2026-07-18 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='linea',
            name='proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas', to='api_produccion.proceso'),
        ),
        migrations.AddField(
            model_name='paso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipo_oblea',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
