# Generated by Django 6.0.5 on 2026-06-21 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_produccion', '0001_initial'),
        ('api_usuarios', '0002_alter_empleado_estado_alter_empleado_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oblea',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='oblea', to='api_produccion.estado_oblea'),
        ),
        migrations.AlterField(
            model_name='oblea',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='oblea', to='api_produccion.orden'),
        ),
        migrations.AlterField(
            model_name='oblea',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='oblea', to='api_produccion.tipo_oblea'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orden', to='api_usuarios.empleado'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orden', to='api_produccion.estado_orden'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orden', to='api_produccion.proceso'),
        ),
        migrations.AlterField(
            model_name='pasoproceso',
            name='paso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paso', to='api_produccion.paso'),
        ),
        migrations.AlterField(
            model_name='pasoproceso',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paso', to='api_produccion.proceso'),
        ),
        migrations.DeleteModel(
            name='Paso_Realizado',
        ),
    ]
