# Generated by Django 6.0.5 on 2026-07-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_produccion', '0002_linea_activo_linea_proceso_paso_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paso_realizado',
            name='scrap',
            field=models.IntegerField(default=0),
        ),
    ]
