# Generated by Django 6.0.5 on 2026-07-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_produccion', '0003_paso_realizado_scrap'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipo_oblea',
            table='tipo_oblea',
        ),
    ]
