# Generated by Django 6.0.5 on 2026-07-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_produccion', '0004_alter_tipo_oblea_table'),
    ]

    operations = [
        migrations.RunSQL(
            sql= '''
                CREATE TRIGGER t_prueba_alerta_exito
                BEFORE INSERT ON pieza
                FOR EACH ROW
                BEGIN
                    INSERT into alerta (`descripcion`,`estadoAlerta_id`)
                    VALUES ("Alerta de prueba" , 'sinre');
                END ;
                '''            
        )
    ]
