# Generated by Django 5.2.15 on 2026-07-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_produccion', '0002_oblea_codigoqr'),
        ('api_produccion', '0004_alter_tipo_oblea_table'),
    ]

    operations = [
    ]
