# Generated by Django 6.0.5 on 2026-07-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_produccion', '0005_auto_20260722_1102'),
        ('api_produccion', '0005_merge_0002_oblea_codigoqr_0004_alter_tipo_oblea_table'),
    ]

    operations = [
    ]
