# Generated by Django 6.0.5 on 2026-07-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_produccion', '0007_alter_historial_defectos_id_alter_lineaproceso_id_and_more'),
    ]

    operations = [ 
                migrations.RunSQL(
                            sql='''
                            
                            '''
                        ),
    ]
