# Generated by Django 6.0.5 on 2026-07-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_produccion', '0009_alter_historial_defectos_id_alter_lineaproceso_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linea',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='paso',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tipo_oblea',
            name='activo',
        ),
        migrations.AlterField(
            model_name='historial_defectos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lineaproceso',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='maquinapaso',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pasoproceso',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='procesopieza',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
