# Generated by Django 6.0.5 on 2026-07-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_produccion', '0012_alter_historial_defectos_id_alter_lineaproceso_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defecto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='defecto',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
