# Generated by Django 6.0.5 on 2026-07-29 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_produccion', '0013_defecto_activo_defecto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defecto',
            name='categoria',
        ),
        migrations.CreateModel(
            name='PasoDefecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defecto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paso_defecto', to='api_produccion.defecto')),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paso_defecto', to='api_produccion.paso')),
            ],
            options={
                'db_table': 'paso-defecto',
                'constraints': [models.UniqueConstraint(fields=('paso', 'defecto'), name='uk_paso_defecto')],
            },
        ),
    ]
