# Generated by Django 6.0.5 on 2026-07-30 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_produccion', '0014_remove_defecto_categoria_pasodefecto'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''CREATE OR REPLACE TRIGGER t_actualizar_dies_por_paso
            after insert on paso_realizado
            for EACH ROW
            BEGIN
                if (new.scrap != 0)
                THEN
                    UPDATE oblea
                    set diesGenerados = diesGenerados - new.scrap
                    where numero = new.oblea_id;
                end if;
                
            END;
            '''
        ),
        migrations.RunSQL(
            sql = '''CREATE OR REPLACE TRIGGER t_scrap_excedente_del_permitido
AFTER UPDATE ON oblea
FOR EACH ROW
BEGIN
    DECLARE v_limite_permitido DECIMAL(10,2);

    SELECT (tob.cantidadDies * 0.95) INTO v_limite_permitido
    FROM orden as o
    JOIN tipo_oblea as tob ON tob.codigo = o.tipoOblea_id
    WHERE o.numero = NEW.orden_id;

    IF NEW.diesGenerados < v_limite_permitido THEN
        UPDATE orden
        SET estado_id = 'enhol'
        WHERE numero = NEW.orden_id;
    END IF;
END;
'''
        ),
         migrations.RunSQL(
                    sql = '''
CREATE OR REPLACE TRIGGER t_alerta_stock_critico
AFTER INSERT ON orden
FOR EACH ROW
BEGIN

    INSERT INTO alerta (`descripcion`,`estadoAlerta_id`) 
    SELECT 
        'Stock Insuficiente',
        'sinre'
    FROM `proceso-pieza` pp
    JOIN pieza p ON p.codigo = pp.pieza_id
    WHERE pp.proceso_id = NEW.proceso_id
      AND p.stockActual < p.stockMinimo;

END;
'''
                ),
          migrations.RunSQL(
                     sql = '''
CREATE OR REPLACE TRIGGER t_alerta_stock_insuficiente
BEFORE INSERT ON orden
FOR EACH ROW
BEGIN
    DECLARE v_pieza_sin_stock VARCHAR(100);
    
    SELECT p.nombre INTO v_pieza_sin_stock
    FROM `proceso-pieza` pp
    JOIN tipo_oblea tob ON tob.codigo = NEW.tipoOblea_id
    JOIN pieza p ON p.codigo = pp.pieza_id
    WHERE pp.proceso_id = NEW.proceso_id
      AND p.stockActual < (tob.cantidadDies * pp.cantPiezas)
    LIMIT 1;

    IF v_pieza_sin_stock IS NOT NULL THEN
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'Stock insuficiente de algunas de las piezas';
    END IF;

    UPDATE pieza p
    JOIN `proceso-pieza` pp ON p.codigo = pp.pieza_id
    JOIN tipo_oblea tob ON tob.codigo = NEW.tipoOblea_id
    SET p.stockActual = p.stockActual - (tob.cantidadDies * pp.cantPiezas)
    WHERE pp.proceso_id = NEW.proceso_id;

END;
'''
                 ),
           migrations.RunSQL(
                      sql = ''''''
                  ),
    ]
