# Generated by Django 6.0.5 on 2026-08-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_produccion', '0016_estado_orden_enhol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linea',
            options={'ordering': ['codigo']},
        ),
        migrations.AlterField(
            model_name='linea',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
