# Generated by Django 6.0.5 on 2026-07-05 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Maquina',
            fields=[
                ('clave', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(default='Estado genérico', max_length=15, unique=True)),
            ],
            options={
                'db_table': 'estado_maquina',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Maquina',
            fields=[
                ('clave', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'tipo_maquina',
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('numSerie', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Máquina genérica', max_length=30, unique=True)),
                ('fechaReg', models.TimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquina', to='api_usuarios.empleado')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquina', to='api_maquinaria.estado_maquina')),
            ],
            options={
                'db_table': 'maquina',
            },
        ),
    ]
