# Generated by Django 6.0.5 on 2026-06-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(default='', max_length=5)),
                ('descripcion', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numSerie', models.CharField(default='ABCDE', max_length=5)),
                ('fechaReg', models.TimeField(auto_now_add=True)),
                ('tipoMaquina', models.CharField(default='', max_length=5)),
                ('estado', models.CharField(default='', max_length=5)),
                ('empleado', models.IntegerField(default=0)),
                ('linea', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(default='', max_length=5)),
                ('descripcion', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
