# Generated by Django 6.0.5 on 2026-06-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_maquinaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estado_maquina',
            table='estado_maquina',
        ),
        migrations.AlterModelTable(
            name='maquina',
            table='maquina',
        ),
        migrations.AlterModelTable(
            name='tipo_maquina',
            table='tipo_maquina',
        ),
    ]
