# Generated by Django 6.0.5 on 2026-07-08 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_maquinaria', '0001_initial'),
        ('api_produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquina', to='api_produccion.linea'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='tipoMaquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquina', to='api_maquinaria.tipo_maquina'),
        ),
    ]
