# Generated by Django 6.0.5 on 2026-08-05 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_maquinaria', '0002_initial'),
        ('api_produccion', '0017_alter_linea_options_alter_linea_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquina', to='api_produccion.linea'),
        ),
    ]
