# Generated by Django 6.0.5 on 2026-07-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_maquinaria', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='fechaReg',
            field=models.DateField(auto_now_add=True),
        ),
    ]
