# Generated by Django 6.0.5 on 2026-07-20 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_maquinaria', '0003_maquina_activo_alter_maquina_fechareg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='activo',
        ),
    ]
