# Generated by Django 6.0.5 on 2026-07-20 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_maquinaria', '0004_remove_maquina_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado_maquina',
            old_name='clave',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='tipo_maquina',
            old_name='clave',
            new_name='codigo',
        ),
    ]
