# Generated by Django 6.0.5 on 2026-06-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=40)),
                ('primerApell', models.CharField(default='', max_length=40)),
                ('seguApell', models.CharField(default='', max_length=40)),
                ('rfc', models.CharField(default='', max_length=13)),
                ('email', models.CharField(default='', max_length=50)),
                ('fechaReg', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='', max_length=5)),
                ('rol', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=5)),
                ('descripcion', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=5)),
                ('descripcion', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
