# Generated by Django 6.0.5 on 2026-07-02 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Empleado',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(default='Estado de empleado genérico', max_length=15, unique=True)),
            ],
            options={
                'db_table': 'estado_empleado',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(default='Rol genérico', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('primerApell', models.CharField(max_length=40)),
                ('seguApell', models.CharField(max_length=40)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('fechaReg', models.DateField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='empleado', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='empleados', to='api_usuarios.estado_empleado')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='empleados', to='api_usuarios.rol')),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
    ]
