# Generated by Django 6.0.5 on 2026-06-24 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='email',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='empleados', to='api_usuarios.estado_empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='empleados', to='api_usuarios.rol'),
        ),
    ]
