# Generated by Django 6.0.5 on 2026-07-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='seguApell',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
