# Generated by Django 6.0.5 on 2026-07-23 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_usuarios', '0002_alter_empleado_seguapell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fechaReg',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.ForeignKey(default='act', on_delete=django.db.models.deletion.RESTRICT, related_name='empleados', to='api_usuarios.estado_empleado'),
        ),
    ]
