# Generated by Django 5.2.15 on 2026-07-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Pieza genérica', max_length=20, unique=True)),
                ('descripcion', models.CharField(default='Descripción genérica', max_length=80)),
                ('stockMinimo', models.IntegerField(default=0)),
                ('stockActual', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='piezas/')),
            ],
            options={
                'db_table': 'pieza',
            },
        ),
    ]
