# Generated by Django 6.0.5 on 2026-06-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='ABCDE', max_length=5)),
                ('nombre', models.CharField(default='Nombre de pieza', max_length=64)),
                ('descripcion', models.CharField(default='Descripción', max_length=40)),
                ('stockMinimo', models.IntegerField(default=0)),
                ('stockActual', models.IntegerField(default=0)),
            ],
        ),
    ]
