# Generated by Django 6.0.5 on 2026-06-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pieza',
            table='pieza',
        ),
    ]
