# Generated by Django 5.2.15 on 2026-07-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_inventario', '0004_alter_movimientoinventario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
