# Generated by Django 6.0.5 on 2026-08-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(default='07:00')),
                ('hora_fin', models.TimeField(default='17:00')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Horario del sistema',
                'verbose_name_plural': 'Horario del sistema',
            },
        ),
    ]
