# Generated by Django 6.0.5 on 2026-08-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inactividad_minutos', models.PositiveIntegerField(default=30)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de la app móvil',
                'verbose_name_plural': 'Configuración de la app móvil',
            },
        ),
    ]
